CREATE TABLE Tag (Id INTEGER PRIMARY KEY UNIQUE, Name VARCHAR (100));
INSERT INTO Tag (Id, Name) VALUES (1, 'Before Breakfast');
INSERT INTO Tag (Id, Name) VALUES (2, 'Before Lunch');
INSERT INTO Tag (Id, Name) VALUES (3, 'Before Dinner');
INSERT INTO Tag (Id, Name) VALUES (4, 'Before Bed');
INSERT INTO Tag (Id, Name) VALUES (5, 'After Bed');
INSERT INTO Tag (Id, Name) VALUES (6, 'After Breakfast');
INSERT INTO Tag (Id, Name) VALUES (7, 'After Lunch');
INSERT INTO Tag (Id, Name) VALUES (8, 'After Dinner');
INSERT INTO Tag (Id, Name) VALUES (9, 'Before Activity');
INSERT INTO Tag (Id, Name) VALUES (10, 'During Activity');
INSERT INTO Tag (Id, Name) VALUES (11, 'After Activity');
INSERT INTO Tag (Id, Name) VALUES (12, 'At Night');
INSERT INTO Tag (Id, Name) VALUES (13, 'Before Snack');
INSERT INTO Tag (Id, Name) VALUES (14, 'After Snack');
CREATE TABLE MeasurementPeriod (Id INTEGER PRIMARY KEY UNIQUE, Name VARCHAR (50), StartTime TIME, EndTime TIME, ReminderTime TIME, TagId INTEGER REFERENCES Tag (Id));
INSERT INTO MeasurementPeriod (Id, Name, StartTime, EndTime, ReminderTime, TagId) VALUES (1, 'Morning', '05:00', '09:59', '09:59', 1);
INSERT INTO MeasurementPeriod (Id, Name, StartTime, EndTime, ReminderTime, TagId) VALUES (2, 'Midday', '10:00', '14:59', '14:59', 2);
INSERT INTO MeasurementPeriod (Id, Name, StartTime, EndTime, ReminderTime, TagId) VALUES (3, 'Evening', '15:00', '19:59', '19:59', 3);
INSERT INTO MeasurementPeriod (Id, Name, StartTime, EndTime, ReminderTime, TagId) VALUES (4, 'Before Bed', '20:00', '23:59', '23:59', 4);
CREATE TABLE InjectionType (Id INTEGER PRIMARY KEY, Name TEXT);
CREATE TABLE Injection (Id INTEGER PRIMARY KEY, InputOn DATETIME, Value DECIMAL, InjectionTypeId INT REFERENCES InjectionType (Id));
CREATE TABLE MeasurementInput (Id INTEGER PRIMARY KEY UNIQUE, InputOn DATETIME, Value DECIMAL, SleepComfortLevel INTEGER, IsPreventStepsTaken BOOLEAN DEFAULT (0), TagId INTEGER REFERENCES Tag (Id));
CREATE TABLE MeasurementType (Id INTEGER PRIMARY KEY UNIQUE, Name VARCHAR (20));
INSERT INTO MeasurementType (Id, Name) VALUES (1, 'mg/dl');
INSERT INTO MeasurementType (Id, Name) VALUES (2, 'mmol/l');
CREATE TABLE Prediction (Id INTEGER PRIMARY KEY, Value INTEGER, CreatedOn DATETIME);
CREATE TABLE User (Id INTEGER PRIMARY KEY NOT NULL UNIQUE, BirthYear VARCHAR (6), MeasurementTypeId INTEGER REFERENCES MeasurementType (Id), Language VARCHAR (50), TimeFormat VARCHAR (50), IllFrom VARCHAR (250), A1C INTEGER, Gender VARCHAR (50));